### ISSUE TITLE
Implementing more algorithms (tracking issue)

### ISSUE THREAD

**Issue by lxndio** [lxndio/aas-benchmark#21]
This issue is used to track which algorithms from the AaS script have already been implemented.

### Single Pattern

- [x] Naive approach
- [x] Knuth-Morris-Pratt
- [x] Shift-And
- [x] BNDM
- [x] BOM

### Full Text Index

- [ ] Ukkonen's Algorithm
- [x] SAIS
- [x] Exact pattern matching
- [x] Backward-Search-Algorithm

### Approximative

- [x] Ukkonen's DP Algorithm
- [x] Error tolerant Shift-And
- [ ] Error tolerant BNDM
- [ ] Error tolerant Backward-Search-Algorithm

### Multiple Patterns

- [x] Naive approach
- [ ] Shift-And
- [x] Aho-Corasick
- [ ] PWM Pattern Matching
